"""
iNHCES O6-S13 Agent 08 — API Documentation PDF Generator
Produces O6_13_API_Documentation.pdf for the nhces-backend REST API.

DATA SOURCE: AMBER — AI-authored documentation template.
Verify all endpoint descriptions against the live OpenAPI schema at /docs
before sharing externally.

TETFund NRF 2025 | Department of Quantity Surveying, ABU Zaria
"""

import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, "01_literature_review"))

from generate_o1_pdfs import (
    DocPDF, sanitize,
    DARK_NAVY, GOLD, LIGHT_BLUE, LABEL_BLUE, WHITE,
    DARK_GREY, MID_GREY, CODE_BG, GREEN_BG, RED_BG,
    PAGE_W, LEFT, LINE_H,
)
from datetime import date

OUTPUT_DIR = os.path.join(_ROOT, "nhces-backend")

AMBER_BG  = (255, 248, 220)
GET_BG    = (210, 235, 255)
POST_BG   = (215, 240, 220)
PUT_BG    = (255, 240, 200)
DELETE_BG = (255, 220, 220)
METHOD_W  = 18
PATH_W    = 70
AUTH_W    = 22
DESC_W    = PAGE_W - METHOD_W - PATH_W - AUTH_W


class ApiDocPDF(DocPDF):
    def header(self):
        self.set_fill_color(*DARK_NAVY)
        self.rect(0, 0, 210, 14, "F")
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*WHITE)
        self.set_xy(5, 4)
        self.cell(PAGE_W, 6, sanitize(
            "iNHCES | TETFund NRF 2025 | ABU Zaria  |  O6-S13 API Documentation"
        ))
        self.set_text_color(*DARK_GREY)
        self.ln(16)

    def footer(self):
        self.set_y(-13)
        self.set_draw_color(*GOLD)
        self.set_line_width(0.4)
        self.line(LEFT, self.get_y(), 198, self.get_y())
        self.set_font("Helvetica", "I", 7.5)
        self.set_text_color(*MID_GREY)
        self.cell(0, 8, sanitize(
            f"O6_13 API Documentation  |  ABU Zaria / TETFund NRF 2025  |  Page {self.page_no()}"
        ), align="C")

    def ds_page(self):
        self.add_page()
        self.set_fill_color(180, 120, 0)
        self.set_text_color(*WHITE)
        self.rect(0, 14, 210, 22, "F")
        self.set_xy(0, 18)
        self.set_font("Helvetica", "B", 13)
        self.cell(210, 8, "DATA SOURCE DECLARATION -- AMBER", align="C", ln=True)
        self.set_font("Helvetica", "", 9)
        self.cell(210, 7, "AI-authored documentation template -- verify against live /docs before external use", align="C", ln=True)
        self.set_text_color(*DARK_GREY)
        self.set_xy(LEFT, 44)
        notes = (
            "This API documentation was generated by GitHub Copilot / Claude Sonnet 4.6 "
            "on " + date.today().strftime("%d %B %Y") + ". "
            "All endpoint descriptions, request/response schemas, and error codes are "
            "derived from the iNHCES source code (nhces-backend/app/). "
            "The authoritative API reference is the live OpenAPI schema at GET /openapi.json "
            "and the Swagger UI at GET /docs. "
            "DATA SOURCE: AMBER. TETFund NRF 2025 | Dept. of Quantity Surveying, ABU Zaria."
        )
        self.set_font("Helvetica", "I", 8.5)
        self.set_text_color(*MID_GREY)
        self.multi_cell(PAGE_W, 5, sanitize(notes))

    def endpoint_title(self, method, path, brief):
        colours = {
            "GET":    GET_BG,
            "POST":   POST_BG,
            "PUT":    PUT_BG,
            "DELETE": DELETE_BG,
        }
        self.ln(4)
        bg = colours.get(method, LIGHT_BLUE)
        self.set_fill_color(*bg)
        self.set_draw_color(*GOLD)
        self.set_line_width(0.3)
        self.set_x(LEFT)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*DARK_NAVY)
        self.cell(METHOD_W, 8, sanitize(method), border=1, fill=True, align="C")
        self.set_font("Courier", "B", 8.5)
        self.cell(PATH_W, 8, sanitize(path), border=1, fill=True)
        self.set_font("Helvetica", "", 8.5)
        self.cell(PAGE_W - METHOD_W - PATH_W, 8, sanitize(brief), border=1, fill=True, ln=True)
        self.set_text_color(*DARK_GREY)

    def field_table(self, rows, col_widths=None):
        """
        rows: list of (name, type, required, description)
        """
        if col_widths is None:
            col_widths = [42, 26, 16, PAGE_W - 42 - 26 - 16]
        headers = ["Field", "Type", "Required", "Description"]
        # Header row
        self.set_fill_color(*DARK_NAVY)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 7.5)
        self.set_x(LEFT)
        for h, w in zip(headers, col_widths):
            self.cell(w, LINE_H, sanitize(h), border=1, fill=True, align="C")
        self.ln()
        # Data rows
        for i, (name, typ, req, desc) in enumerate(rows):
            bg = (248, 250, 255) if i % 2 == 0 else WHITE
            self.set_fill_color(*bg)
            self.set_x(LEFT)
            self.set_font("Courier", "", 7.5)
            self.set_text_color(*DARK_NAVY)
            self.cell(col_widths[0], LINE_H, sanitize(name), border=1, fill=True)
            self.set_font("Helvetica", "I", 7.5)
            self.set_text_color(*MID_GREY)
            self.cell(col_widths[1], LINE_H, sanitize(typ), border=1, fill=True)
            req_bg = (210, 240, 215) if req == "Yes" else (245, 245, 245)
            self.set_fill_color(*req_bg)
            self.cell(col_widths[2], LINE_H, sanitize(req), border=1, fill=True, align="C")
            self.set_fill_color(*bg)
            self.set_font("Helvetica", "", 7.5)
            self.set_text_color(*DARK_GREY)
            self.cell(col_widths[3], LINE_H, sanitize(desc[:58]), border=1, fill=True, ln=True)
        self.ln(2)

    def code(self, text):
        self.ln(1)
        self.set_fill_color(*CODE_BG)
        self.set_draw_color(*MID_GREY)
        self.set_line_width(0.2)
        self.set_x(LEFT)
        self.set_font("Courier", "", 7.5)
        self.set_text_color(*DARK_GREY)
        self.multi_cell(PAGE_W, 4.2, sanitize(text), border=1, fill=True)
        self.ln(2)

    def note(self, text):
        self.ln(1)
        self.set_fill_color(*LIGHT_BLUE)
        self.set_draw_color(*GOLD)
        self.set_line_width(0.3)
        self.set_x(LEFT)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*DARK_NAVY)
        self.multi_cell(PAGE_W, 5, sanitize(text), border=1, fill=True)
        self.ln(2)

    def error_table(self, rows):
        self.set_fill_color(*DARK_NAVY)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 7.5)
        self.set_x(LEFT)
        for h, w in [("Code", 18), ("Status", 40), ("Condition", PAGE_W - 58)]:
            self.cell(w, LINE_H, h, border=1, fill=True, align="C")
        self.ln()
        for code, status, condition in rows:
            bg = (255, 240, 240) if str(code).startswith("4") or str(code).startswith("5") else (240, 255, 245)
            self.set_fill_color(*bg)
            self.set_x(LEFT)
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(*DARK_NAVY)
            self.cell(18, LINE_H, str(code), border=1, fill=True, align="C")
            self.set_font("Helvetica", "", 8)
            self.cell(40, LINE_H, sanitize(status), border=1, fill=True)
            self.set_text_color(*DARK_GREY)
            self.cell(PAGE_W - 58, LINE_H, sanitize(condition), border=1, fill=True, ln=True)
        self.ln(3)


# ── Document builder ───────────────────────────────────────────────────────────

def generate():
    pdf = ApiDocPDF(
        doc_name="O6_13 API Documentation",
        doc_subtitle="iNHCES REST API Reference",
    )

    # ── Cover ──────────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_fill_color(*DARK_NAVY)
    pdf.rect(0, 18, 210, 55, "F")
    pdf.set_xy(0, 26)
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(*WHITE)
    pdf.cell(210, 9, sanitize("iNHCES REST API Reference"), align="C", ln=True)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(200, 215, 235)
    pdf.cell(210, 7, sanitize("O6-S13: Agent 08 - API Documentation"), align="C", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*LIGHT_BLUE)
    pdf.cell(210, 6, sanitize("Intelligent National Housing Cost Estimating System (iNHCES)"), align="C", ln=True)
    pdf.cell(210, 6, sanitize("TETFund NRF 2025  |  Department of Quantity Surveying, ABU Zaria"), align="C", ln=True)
    pdf.set_draw_color(*GOLD)
    pdf.set_line_width(0.8)
    pdf.line(30, 76, 180, 76)
    pdf.set_xy(LEFT, 84)
    pdf.set_text_color(*DARK_GREY)
    meta = [
        ("Base URL (dev):",    "http://localhost:8000"),
        ("Base URL (prod):",   "https://nhces-api.up.railway.app"),
        ("OpenAPI schema:",    "GET /openapi.json"),
        ("Swagger UI:",        "GET /docs"),
        ("ReDoc:",             "GET /redoc"),
        ("Version:",           "1.0.0"),
        ("Date:",              date.today().strftime("%d %B %Y")),
        ("Auth:",              "Supabase GoTrue JWT (Bearer token, HS256)"),
        ("Data Source:",       "AMBER - AI-authored; verify against live /docs"),
    ]
    for label, val in meta:
        pdf.set_x(LEFT)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*DARK_NAVY)
        pdf.cell(42, 6.5, sanitize(label))
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*DARK_GREY)
        pdf.cell(PAGE_W - 42, 6.5, sanitize(val), ln=True)

    # ── DATA SOURCE ────────────────────────────────────────────────────────────
    pdf.ds_page()

    # ── 1. Overview ────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("1  Overview")
    pdf.body(
        "The iNHCES REST API is built with FastAPI 0.110 and provides ML-based "
        "Nigerian housing construction cost estimation. The API integrates a "
        "LightGBM champion model (MAPE 13.66%, R^2 0.91) trained on 14 "
        "macroeconomic features, SHAP explainability, temporal cost projections "
        "at 1yr / 3yr / 5yr horizons, project management (CRUD), PDF report "
        "generation to Cloudflare R2, and Airflow pipeline monitoring."
    )

    pdf.sub_heading("Authentication")
    pdf.body(
        "Protected endpoints require a Supabase GoTrue JWT passed as a "
        "Bearer token in the Authorization header. Tokens are issued by the "
        "Supabase Auth service after login. The backend validates tokens using "
        "python-jose (HS256, SUPABASE_JWT_SECRET)."
    )
    pdf.code("Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...")

    pdf.sub_heading("Roles")
    pdf.field_table([
        ("qsprofessional", "string", "No", "Default role for registered users"),
        ("researcher",     "string", "No", "Access to /pipeline + research data"),
        ("admin",          "string", "No", "Full access"),
    ], col_widths=[42, 22, 16, PAGE_W - 42 - 22 - 16])

    pdf.sub_heading("Data Freshness Levels")
    pdf.field_table([
        ("GREEN", "string", "--", "Live API / real measured instrument"),
        ("AMBER", "string", "--", "AI-authored template or derived estimate"),
        ("RED",   "string", "--", "Fully synthetic -- must replace before publication"),
    ], col_widths=[22, 22, 14, PAGE_W - 22 - 22 - 14])

    pdf.sub_heading("Common Response Fields")
    pdf.body("All error responses follow FastAPI's default structure:")
    pdf.code('{"detail": "Error message describing the problem"}')

    pdf.sub_heading("Endpoint Summary")
    # Route table header
    pdf.set_fill_color(*DARK_NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_x(LEFT)
    for h, w in [("Method", METHOD_W), ("Path", PATH_W), ("Auth", AUTH_W), ("Description", DESC_W)]:
        pdf.cell(w, LINE_H + 1, h, border=1, fill=True, align="C")
    pdf.ln()
    routes = [
        ("GET",    "/",                  "None",     "System health and version"),
        ("GET",    "/health",            "None",     "DB + ML model status"),
        ("GET",    "/docs",              "None",     "Swagger UI (interactive)"),
        ("GET",    "/openapi.json",      "None",     "OpenAPI 3.1 schema"),
        ("POST",   "/estimate",          "None",     "ML cost estimation with SHAP + projections"),
        ("GET",    "/macro",             "None",     "Latest 7 macroeconomic variables"),
        ("GET",    "/macro/history",     "None",     "Historical series for one variable"),
        ("GET",    "/projects",          "Optional", "List user projects (empty if unauthed)"),
        ("POST",   "/projects",          "Required", "Create project"),
        ("GET",    "/projects/{id}",     "Required", "Get single project"),
        ("PUT",    "/projects/{id}",     "Required", "Update project"),
        ("DELETE", "/projects/{id}",     "Required", "Delete project"),
        ("POST",   "/reports",           "Optional", "Generate PDF report -> R2 -> presigned URL"),
        ("GET",    "/reports",           "Optional", "List user reports (empty if unauthed)"),
        ("GET",    "/pipeline",          "None",     "Airflow DAG health (9 DAGs)"),
    ]
    colours = {"GET": GET_BG, "POST": POST_BG, "PUT": PUT_BG, "DELETE": DELETE_BG}
    for method, path, auth, desc in routes:
        bg = colours.get(method, LIGHT_BLUE)
        pdf.set_fill_color(*bg)
        pdf.set_x(LEFT)
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*DARK_NAVY)
        pdf.cell(METHOD_W, LINE_H, method, border=1, fill=True, align="C")
        pdf.set_font("Courier", "", 7.5)
        pdf.cell(PATH_W, LINE_H, path, border=1, fill=True)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.cell(AUTH_W, LINE_H, auth, border=1, fill=True, align="C")
        pdf.set_text_color(*DARK_GREY)
        pdf.cell(DESC_W, LINE_H, desc, border=1, fill=True, ln=True)
    pdf.ln(2)

    # ── 2. Health ──────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("2  Health Endpoints")

    pdf.endpoint_title("GET", "/", "System info and operational status")
    pdf.body("Returns the API name, version, environment, and link to the Swagger UI. No authentication required.")
    pdf.sub_heading("Response 200 OK")
    pdf.code(
        '{\n'
        '  "system":      "iNHCES API",\n'
        '  "version":     "1.0.0",\n'
        '  "status":      "operational",\n'
        '  "environment": "production",\n'
        '  "docs":        "/docs"\n'
        '}'
    )

    pdf.endpoint_title("GET", "/health", "Liveness + readiness probe")
    pdf.body(
        "Performs a lightweight Supabase query (SELECT id FROM ml_models LIMIT 1) "
        "to verify database connectivity. Returns overall status 'ok' or 'degraded'."
    )
    pdf.sub_heading("Response 200 OK")
    pdf.code(
        '{\n'
        '  "status":   "ok",\n'
        '  "db":       {"status": "ok", "latency_ms": 45, "champion_loaded": true},\n'
        '  "ml_model": "loaded"\n'
        '}'
    )
    pdf.error_table([
        (200, "OK",       "DB reachable, model cached"),
        (200, "degraded", "DB unreachable (status=degraded in body)"),
    ])

    # ── 3. Estimate ────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("3  POST /estimate")
    pdf.body(
        "Runs the iNHCES ML cost estimation pipeline. Fetches live macroeconomic "
        "features from Supabase, runs the LightGBM champion model, computes SHAP "
        "feature importance, generates temporal projections at 1yr / 3yr / 5yr "
        "horizons, and optionally persists the prediction to Supabase."
    )

    pdf.sub_heading("Request Body")
    pdf.field_table([
        ("building_type",     "string (enum)", "No",  "Residential|Commercial|Industrial|Institutional|Mixed Use"),
        ("construction_type", "string (enum)", "No",  "New Build|Renovation|Extension|Fit-Out"),
        ("floor_area_sqm",    "float",         "Yes", "Gross floor area in sqm (0 < x <= 100000)"),
        ("num_floors",        "integer",       "No",  "Number of floors (1-100, default 1)"),
        ("location_state",    "string",        "Yes", "Nigerian state name (2-60 chars)"),
        ("location_zone",     "string (enum)", "No",  "North Central|North East|North West|..."),
        ("project_id",        "UUID4",         "No",  "Link prediction to existing project"),
        ("target_cost_ngn",   "float",         "No",  "Client budget in NGN (optional)"),
    ])

    pdf.sub_heading("Example Request")
    pdf.code(
        'POST /estimate\n'
        'Content-Type: application/json\n\n'
        '{\n'
        '  "building_type":     "Residential",\n'
        '  "construction_type": "New Build",\n'
        '  "floor_area_sqm":    120.0,\n'
        '  "num_floors":        1,\n'
        '  "location_state":    "Kaduna",\n'
        '  "location_zone":     "North West"\n'
        '}'
    )

    pdf.sub_heading("Response 200 OK — Key Fields")
    pdf.field_table([
        ("prediction_id",            "UUID string",   "--", "Unique prediction identifier"),
        ("predicted_cost_per_sqm",   "float (NGN)",   "--", "ML point estimate per square metre"),
        ("total_predicted_cost_ngn", "float (NGN)",   "--", "cost_per_sqm * floor_area_sqm"),
        ("confidence_lower",         "float (NGN)",   "--", "Lower bound (MAPE-derived interval)"),
        ("confidence_upper",         "float (NGN)",   "--", "Upper bound"),
        ("mape_at_prediction",       "float (%)",     "--", "Champion MAPE at time of prediction"),
        ("model_name",               "string",        "--", "e.g. 'LightGBM'"),
        ("model_version",            "string",        "--", "e.g. '1.0.0'"),
        ("data_freshness",           "string",        "--", "GREEN | AMBER | RED"),
        ("shap_top_features",        "ShapItem[]",    "--", "Top SHAP features (feature/label/value)"),
        ("projections",              "Projection[4]", "--", "Current + 1yr + 3yr + 5yr horizons"),
        ("annual_inflation_rate",    "float",         "--", "e.g. 0.25 = 25% p.a."),
        ("is_synthetic",             "boolean",       "--", "True if model or data is synthetic"),
        ("api_response_ms",          "integer",       "--", "Total server processing time"),
    ])

    pdf.error_table([
        (200, "OK",                  "Successful estimation"),
        (422, "Unprocessable Entity","Pydantic validation error (invalid field value)"),
        (503, "Service Unavailable", "Feature preparation failed (DB or data issue)"),
    ])

    pdf.note(
        "NOTE: DB persistence (Supabase INSERT) is non-fatal. "
        "If the insert fails, the 200 response is still returned. "
        "Prediction is stored with user_id='anonymous' when no JWT is provided."
    )

    # ── 4. Macro ───────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("4  Macroeconomic Endpoints")

    pdf.endpoint_title("GET", "/macro", "Latest snapshot of all 7 macro variables")
    pdf.body(
        "Queries 5 Supabase tables (macro_fx, macro_cpi, macro_gdp, macro_interest, "
        "macro_oil) and returns the most recent value for each of the 7 macro "
        "variables used in the ML feature vector."
    )
    pdf.sub_heading("Response 200 OK")
    pdf.code(
        '{\n'
        '  "variables": [\n'
        '    {\n'
        '      "variable":   "ngn_usd",\n'
        '      "label":      "NGN/USD Exchange Rate",\n'
        '      "value":      1580.0,\n'
        '      "unit":       "NGN per USD",\n'
        '      "as_of_date": "2024-12-01",\n'
        '      "source":     "CBN",\n'
        '      "data_level": "GREEN"\n'
        '    },\n'
        '    ... 6 more variables ...\n'
        '  ],\n'
        '  "overall_freshness": "GREEN",\n'
        '  "as_of": "2026-04-27T12:00:00Z"\n'
        '}'
    )
    pdf.sub_heading("Valid Variable Keys")
    pdf.code(
        "ngn_usd  |  ngn_eur  |  ngn_gbp  |  cpi_annual_pct  |\n"
        "gdp_growth_pct  |  lending_rate_pct  |  brent_usd_barrel"
    )

    pdf.endpoint_title("GET", "/macro/history", "Historical series for one variable")
    pdf.sub_heading("Query Parameters")
    pdf.field_table([
        ("variable", "string", "Yes", "One of the 7 valid variable keys above"),
        ("years",    "integer", "No", "Number of years of history (1-25, default 5)"),
    ], col_widths=[30, 22, 16, PAGE_W - 30 - 22 - 16])
    pdf.sub_heading("Example")
    pdf.code("GET /macro/history?variable=ngn_usd&years=5")
    pdf.error_table([
        (200, "OK",          "Returns MacroHistory object with data[] array"),
        (400, "Bad Request", "Unknown variable key"),
        (422, "Validation",  "years < 1 or years > 25"),
    ])

    # ── 5. Projects ────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("5  Projects Endpoints")
    pdf.body(
        "All /projects endpoints operate on the authenticated user's projects only. "
        "Unauthenticated GET requests return an empty list rather than 401."
    )

    pdf.endpoint_title("GET", "/projects", "List authenticated user's projects")
    pdf.sub_heading("Query Parameters")
    pdf.field_table([
        ("page",  "integer", "No", "Page number (>= 1, default 1)"),
        ("limit", "integer", "No", "Items per page (1-100, default 20)"),
    ], col_widths=[26, 22, 16, PAGE_W - 26 - 22 - 16])
    pdf.sub_heading("Response 200 OK")
    pdf.code(
        '{\n'
        '  "items": [{ "id": "...", "title": "...", "floor_area_sqm": 120.0, ... }],\n'
        '  "total": 5,\n'
        '  "page":  1,\n'
        '  "limit": 20\n'
        '}'
    )

    pdf.endpoint_title("POST", "/projects", "Create a new project")
    pdf.sub_heading("Request Body (ProjectCreate)")
    pdf.field_table([
        ("title",             "string",       "Yes", "Project name (3-200 chars)"),
        ("building_type",     "string (enum)","No",  "Same enum as /estimate"),
        ("construction_type", "string (enum)","No",  "Same enum as /estimate"),
        ("floor_area_sqm",    "float",        "Yes", "0 < x <= 100000"),
        ("num_floors",        "integer",      "No",  "1-100, default 1"),
        ("location_state",    "string",       "Yes", "Nigerian state (2-60 chars)"),
        ("location_zone",     "string (enum)","No",  "Geopolitical zone"),
        ("location_lga",      "string",       "No",  "Local government area"),
        ("target_cost_ngn",   "float",        "No",  "Client budget in NGN (> 0)"),
        ("notes",             "string",       "No",  "Free-text notes"),
    ])
    pdf.error_table([
        (201, "Created",             "Project saved to Supabase"),
        (401, "Unauthorized",        "No valid JWT provided"),
        (422, "Unprocessable Entity","Validation error"),
        (503, "Service Unavailable", "Database error"),
    ])

    pdf.endpoint_title("GET", "/projects/{id}", "Get a single project by ID")
    pdf.endpoint_title("PUT", "/projects/{id}", "Update title, status, target_cost_ngn, notes")
    pdf.endpoint_title("DELETE", "/projects/{id}", "Delete project (returns 204 No Content)")
    pdf.error_table([
        (200, "OK",           "Project found and returned"),
        (204, "No Content",   "Project deleted"),
        (401, "Unauthorized", "No valid JWT"),
        (404, "Not Found",    "Project does not exist or belongs to another user"),
    ])

    # ── 6. Reports ─────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("6  Reports Endpoints")

    pdf.endpoint_title("POST", "/reports", "Generate a PDF cost report")
    pdf.body(
        "Generates a 4-page Warm Ivory PDF report (fpdf2) containing the "
        "cost estimate, SHAP chart, temporal projections, and macro data "
        "snapshot. The PDF is uploaded to Cloudflare R2 and a 24-hour "
        "presigned download URL is returned."
    )
    pdf.sub_heading("Request Body")
    pdf.field_table([
        ("project_id",    "string", "Yes", "ID of the project to include in the report"),
        ("prediction_id", "string", "Yes", "ID of the prediction to report on"),
    ], col_widths=[32, 22, 16, PAGE_W - 32 - 22 - 16])
    pdf.sub_heading("Response 200 OK")
    pdf.code(
        '{\n'
        '  "id":             "report-uuid",\n'
        '  "project_id":     "...",\n'
        '  "prediction_id":  "...",\n'
        '  "download_url":   "https://r2.cloudflarestorage.com/...",\n'
        '  "url_expires_at": "2026-04-28T12:00:00Z",\n'
        '  "file_size_bytes": 98304,\n'
        '  "page_count":      4,\n'
        '  "created_at":     "2026-04-27T12:00:00Z"\n'
        '}'
    )
    pdf.note(
        "NOTE: When Cloudflare R2 is not configured (R2_ENDPOINT not set), "
        "the download_url falls back to http://localhost:8000/reports/download/{key}. "
        "This is a development-only placeholder."
    )

    pdf.endpoint_title("GET", "/reports", "List user reports")
    pdf.body("Returns all reports for the authenticated user. Returns empty list if unauthenticated.")

    # ── 7. Pipeline ────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("7  Pipeline Endpoint")

    pdf.endpoint_title("GET", "/pipeline", "Airflow DAG health status")
    pdf.body(
        "Queries the Apache Airflow REST API for the status of all 9 iNHCES "
        "DAGs. Gracefully degrades to 'DEGRADED' when Airflow is unreachable "
        "(returns 200 with overall_health='DEGRADED', not 503). "
        "Airflow credentials are sourced from environment variables."
    )
    pdf.sub_heading("Response 200 OK")
    pdf.code(
        '{\n'
        '  "dags": [\n'
        '    {\n'
        '      "dag_id":         "nhces_daily_fx_oil",\n'
        '      "schedule":       "0 5 * * *",\n'
        '      "description":    "Daily FX + Brent crude prices",\n'
        '      "last_run_state": "success",\n'
        '      "last_run_at":    "2026-04-27T05:00:00Z",\n'
        '      "next_run_at":    "2026-04-28T05:00:00Z",\n'
        '      "data_level":     "RED"\n'
        '    },\n'
        '    ... 8 more DAGs ...\n'
        '  ],\n'
        '  "overall_health": "OK",\n'
        '  "checked_at":     "2026-04-27T12:00:00Z"\n'
        '}'
    )
    pdf.sub_heading("DAG Registry")
    dags = [
        ("nhces_daily_fx_oil",     "0 5 * * *",       "Daily FX + Brent crude prices",           "RED"),
        ("nhces_weekly_materials", "0 5 * * 1",        "Weekly cement + iron rod prices",         "RED"),
        ("nhces_weekly_property",  "0 5 * * 2",        "Weekly property listing prices",          "RED"),
        ("nhces_monthly_macro",    "0 5 1 * *",         "Monthly CPI, lending rate, PMS prices",   "GREEN"),
        ("nhces_quarterly_niqs",   "manual",            "Quarterly NIQS unit rates (manual)",      "RED"),
        ("nhces_quarterly_nbs",    "0 5 1 1,4,7,10 *", "Quarterly NBS stats",                     "RED"),
        ("nhces_worldbank_annual", "0 5 2 1 *",         "Annual World Bank GDP + CPI refresh",     "GREEN"),
        ("nhces_retrain_weekly",   "0 1 * * 0",         "Weekly ML champion retrain",              "AMBER"),
        ("nhces_drift_monitor",    "0 17 * * *",        "Daily PSI drift detection",               "AMBER"),
    ]
    pdf.set_fill_color(*DARK_NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_x(LEFT)
    for h, w in [("DAG ID", 54), ("Schedule", 40), ("Description", 72), ("Level", 20)]:
        pdf.cell(w, LINE_H, h, border=1, fill=True, align="C")
    pdf.ln()
    level_colours = {"RED": (255, 225, 225), "AMBER": (255, 245, 210), "GREEN": (220, 245, 225)}
    for dag_id, sched, desc, level in dags:
        bg = level_colours.get(level, WHITE)
        pdf.set_fill_color(*bg)
        pdf.set_x(LEFT)
        pdf.set_font("Courier", "", 7)
        pdf.set_text_color(*DARK_NAVY)
        pdf.cell(54, LINE_H, dag_id, border=1, fill=True)
        pdf.set_font("Courier", "", 7)
        pdf.cell(40, LINE_H, sched, border=1, fill=True)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*DARK_GREY)
        pdf.cell(72, LINE_H, sanitize(desc), border=1, fill=True)
        pdf.cell(20, LINE_H, level, border=1, fill=True, align="C")
        pdf.ln()
    pdf.ln(3)

    # ── 8. ML Feature Vector ───────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("8  ML Feature Vector Reference")
    pdf.body(
        "The LightGBM champion model expects a 14-feature vector in the order "
        "below. Features are derived from macroeconomic time series stored in "
        "Supabase. I(1) variables use first differences; I(2)* exchange rates "
        "use percentage returns."
    )
    features = [
        ("d_gdp_growth_pct",        "float", "I(1) first difference",     "GDP growth rate year-on-year change"),
        ("d_cpi_annual_pct",        "float", "I(1) first difference",     "CPI inflation annual change"),
        ("d_lending_rate_pct",      "float", "I(1) first difference",     "Lending rate annual change"),
        ("d_brent_usd_barrel",      "float", "I(1) first difference",     "Brent crude USD change"),
        ("ret_ngn_usd",             "float", "I(2)* % return",            "NGN/USD percentage change"),
        ("ret_ngn_eur",             "float", "I(2)* % return",            "NGN/EUR percentage change"),
        ("ret_ngn_gbp",             "float", "I(2)* % return",            "NGN/GBP percentage change"),
        ("lag1_d_gdp_growth_pct",   "float", "Lag-1 of d_gdp_growth_pct", "Previous period GDP growth diff"),
        ("lag1_d_cpi_annual_pct",   "float", "Lag-1 of d_cpi_annual_pct", "Previous period CPI diff"),
        ("lag1_d_lending_rate_pct", "float", "Lag-1",                     "Previous period lending rate diff"),
        ("lag1_d_brent_usd_barrel", "float", "Lag-1",                     "Previous period Brent diff"),
        ("lag1_ret_ngn_usd",        "float", "Lag-1 of ret_ngn_usd",      "Previous period NGN/USD return"),
        ("lag1_ret_ngn_eur",        "float", "Lag-1 of ret_ngn_eur",      "Previous period NGN/EUR return"),
        ("lag1_ret_ngn_gbp",        "float", "Lag-1 of ret_ngn_gbp",      "Previous period NGN/GBP return"),
    ]
    pdf.field_table(
        [(name, typ, transform, desc) for name, typ, transform, desc in features],
        col_widths=[52, 14, 38, PAGE_W - 52 - 14 - 38],
    )
    pdf.sub_heading("SHAP Rankings (O5 Training Data)")
    pdf.body(
        "Based on O5 training (n=22 years, 2001-2022), the dominant features "
        "are: ret_ngn_usd (45%) > d_cpi_annual_pct (25.5%) > ret_ngn_eur (11.6%) "
        "> d_brent_usd_barrel (10.9%). SHAP values are near-zero at n=22 -- "
        "values will become more interpretable with real survey data."
    )

    # ── 9. Error Reference ─────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("9  Error Code Reference")
    pdf.body("Standard HTTP status codes returned by the iNHCES API:")
    pdf.error_table([
        (200, "OK",                  "Request succeeded"),
        (201, "Created",             "Resource created (POST /projects)"),
        (204, "No Content",          "Resource deleted (DELETE /projects/{id})"),
        (400, "Bad Request",         "Invalid query parameter (e.g. unknown macro variable)"),
        (401, "Unauthorized",        "Missing or invalid JWT token"),
        (403, "Forbidden",           "Authenticated but insufficient role"),
        (404, "Not Found",           "Resource does not exist or belongs to another user"),
        (422, "Unprocessable Entity","Pydantic validation error in request body"),
        (503, "Service Unavailable", "Backend dependency failure (DB, feature prep)"),
    ])
    pdf.sub_heading("Error Response Format")
    pdf.code(
        '{\n'
        '  "detail": "Human-readable error message"\n'
        '}\n\n'
        '// Pydantic 422 errors include field-level detail:\n'
        '{\n'
        '  "detail": [\n'
        '    {\n'
        '      "type":  "greater_than",\n'
        '      "loc":   ["body", "floor_area_sqm"],\n'
        '      "msg":   "Input should be greater than 0",\n'
        '      "input": 0\n'
        '    }\n'
        '  ]\n'
        '}'
    )

    pdf.sub_heading("API Docs Links")
    pdf.info_box(
        "Interactive API docs (Swagger UI): GET /docs\n"
        "Alternative docs (ReDoc):          GET /redoc\n"
        "OpenAPI 3.1 JSON schema:           GET /openapi.json\n"
        "DATA SOURCE: AMBER -- AI-authored documentation. "
        "The authoritative reference is the live OpenAPI schema at /openapi.json. "
        "TETFund NRF 2025 | Dept. of Quantity Surveying, ABU Zaria."
    )

    # Save
    out_path = os.path.join(OUTPUT_DIR, "O6_13_API_Documentation.pdf")
    pdf.output(out_path)
    print(f"[OK] {out_path}")
    print(f"     Pages: {pdf.page}")


if __name__ == "__main__":
    generate()
