"""
iNHCES O6-S14 Agent 09/10 — Deployment Documentation PDF Generator
Produces O6_14_Deployment_Guide.pdf covering Dockerfile, Railway, Vercel,
GitHub Actions CI/CD, and Airflow DAG configuration.

DATA SOURCE: AMBER — AI-authored deployment guide template.
Verify all URLs, Railway service IDs, and environment variable names against
the live Railway/Vercel/Supabase dashboards before use.

TETFund NRF 2025 | Department of Quantity Surveying, ABU Zaria
"""

import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, "01_literature_review"))

from generate_o1_pdfs import (
    DocPDF, sanitize,
    DARK_NAVY, GOLD, LIGHT_BLUE, LABEL_BLUE, WHITE,
    DARK_GREY, MID_GREY, CODE_BG, GREEN_BG, RED_BG,
    PAGE_W, LEFT, LINE_H,
)
from datetime import date

OUTPUT_DIR = os.path.join(_ROOT, "nhces-backend")
AMBER_BG = (255, 248, 220)


class DeployPDF(DocPDF):
    def header(self):
        self.set_fill_color(*DARK_NAVY)
        self.rect(0, 0, 210, 14, "F")
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*WHITE)
        self.set_xy(5, 4)
        self.cell(PAGE_W, 6, sanitize(
            "iNHCES | TETFund NRF 2025 | ABU Zaria  |  O6-S14 Deployment Guide"
        ))
        self.set_text_color(*DARK_GREY)
        self.ln(16)

    def footer(self):
        self.set_y(-13)
        self.set_draw_color(*GOLD)
        self.set_line_width(0.4)
        self.line(LEFT, self.get_y(), 198, self.get_y())
        self.set_font("Helvetica", "I", 7.5)
        self.set_text_color(*MID_GREY)
        self.cell(0, 8, sanitize(
            f"O6_14 Deployment Guide  |  ABU Zaria / TETFund NRF 2025  |  Page {self.page_no()}"
        ), align="C")

    def ds_page(self):
        self.add_page()
        self.set_fill_color(180, 120, 0)
        self.set_text_color(*WHITE)
        self.rect(0, 14, 210, 22, "F")
        self.set_xy(0, 18)
        self.set_font("Helvetica", "B", 13)
        self.cell(210, 8, "DATA SOURCE DECLARATION -- AMBER", align="C", ln=True)
        self.set_font("Helvetica", "", 9)
        self.cell(210, 7, "AI-authored deployment template -- verify all credentials + service IDs before use", align="C", ln=True)
        self.set_text_color(*DARK_GREY)
        self.set_xy(LEFT, 44)
        notes = (
            "This deployment guide was generated by GitHub Copilot / Claude Sonnet 4.6 "
            "on " + date.today().strftime("%d %B %Y") + ". "
            "All Railway service URLs, Vercel project IDs, Supabase credentials, and "
            "Cloudflare R2 endpoints are placeholder values. "
            "Replace them with real values from the respective dashboards before deploying. "
            "DATA SOURCE: AMBER. TETFund NRF 2025 | Dept. of Quantity Surveying, ABU Zaria."
        )
        self.set_font("Helvetica", "I", 8.5)
        self.set_text_color(*MID_GREY)
        self.multi_cell(PAGE_W, 5, sanitize(notes))

    def step(self, n, text):
        self.ln(3)
        self.set_fill_color(*DARK_NAVY)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 9)
        self.set_x(LEFT)
        self.cell(8, 7, str(n), border=0, fill=True, align="C")
        self.set_fill_color(*LIGHT_BLUE)
        self.set_text_color(*DARK_NAVY)
        self.cell(PAGE_W - 8, 7, sanitize(f"  {text}"), border=0, fill=True, ln=True)
        self.set_text_color(*DARK_GREY)


def generate():
    pdf = DeployPDF(
        doc_name="O6_14 Deployment Guide",
        doc_subtitle="iNHCES Infrastructure & CI/CD",
    )

    # ── Cover ──────────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_fill_color(*DARK_NAVY)
    pdf.rect(0, 18, 210, 55, "F")
    pdf.set_xy(0, 26)
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(*WHITE)
    pdf.cell(210, 9, sanitize("iNHCES Deployment Guide"), align="C", ln=True)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(200, 215, 235)
    pdf.cell(210, 7, sanitize("O6-S14: Agents 09+10 - Infrastructure & CI/CD"), align="C", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*LIGHT_BLUE)
    pdf.cell(210, 6, sanitize("Intelligent National Housing Cost Estimating System (iNHCES)"), align="C", ln=True)
    pdf.cell(210, 6, sanitize("TETFund NRF 2025  |  Department of Quantity Surveying, ABU Zaria"), align="C", ln=True)
    pdf.set_draw_color(*GOLD)
    pdf.set_line_width(0.8)
    pdf.line(30, 76, 180, 76)
    pdf.set_xy(LEFT, 84)
    meta = [
        ("Backend:",         "FastAPI 0.110 + Uvicorn -- Railway (Docker)"),
        ("Frontend:",        "Next.js 14.2 App Router -- Vercel"),
        ("Database:",        "Supabase PostgreSQL (managed)"),
        ("ML Registry:",     "MLflow -- Railway service"),
        ("Storage:",         "Cloudflare R2 (S3-compatible)"),
        ("Orchestration:",   "Apache Airflow -- Railway service"),
        ("CI/CD:",           "GitHub Actions (test -> build -> deploy)"),
        ("Date:",            date.today().strftime("%d %B %Y")),
        ("Data Source:",     "AMBER - AI-authored; verify all credentials"),
    ]
    for label, val in meta:
        pdf.set_x(LEFT)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*DARK_NAVY)
        pdf.cell(40, 6.5, sanitize(label))
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*DARK_GREY)
        pdf.cell(PAGE_W - 40, 6.5, sanitize(val), ln=True)

    # ── DATA SOURCE ────────────────────────────────────────────────────────────
    pdf.ds_page()

    # ── 1. Architecture Overview ───────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("1  Deployment Architecture Overview")
    pdf.body(
        "iNHCES uses a cloud-native microservices architecture with each component "
        "deployed as an independent service. The frontend (Vercel) proxies all API "
        "calls to the backend (Railway) via rewrite rules in vercel.json, keeping "
        "browser credentials out of the public domain."
    )
    pdf.sub_heading("Service Map")
    services = [
        ("nhces-frontend",  "Vercel",   "Next.js 14 SSR",          "https://nhces.vercel.app"),
        ("nhces-backend",   "Railway",  "FastAPI + LightGBM",       "https://nhces-api.up.railway.app"),
        ("nhces-db",        "Supabase", "PostgreSQL + RLS + Auth",  "https://<ref>.supabase.co"),
        ("inhces-storage",   "Cloudflare R2", "Object storage",      "https://<acct>.r2.cloudflarestorage.com"),
        ("nhces-mlflow",    "Railway",  "MLflow tracking server",   "http://<svc>.railway.app:5000"),
        ("nhces-airflow",   "Railway",  "Apache Airflow 2.8",       "http://<svc>.railway.app:8080"),
    ]
    pdf.set_fill_color(*DARK_NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_x(LEFT)
    for h, w in [("Service", 38), ("Platform", 28), ("Stack", 50), ("URL", PAGE_W - 38 - 28 - 50)]:
        pdf.cell(w, LINE_H + 1, h, border=1, fill=True, align="C")
    pdf.ln()
    for svc, plat, stack, url in services:
        pdf.set_fill_color(248, 250, 255)
        pdf.set_text_color(*DARK_NAVY)
        pdf.set_x(LEFT)
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.cell(38, LINE_H, sanitize(svc), border=1, fill=True)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.cell(28, LINE_H, sanitize(plat), border=1, fill=True)
        pdf.cell(50, LINE_H, sanitize(stack), border=1, fill=True)
        pdf.set_font("Courier", "", 6.5)
        pdf.set_text_color(*MID_GREY)
        pdf.cell(PAGE_W - 38 - 28 - 50, LINE_H, sanitize(url), border=1, fill=True, ln=True)
    pdf.ln(3)

    pdf.sub_heading("Data Flow (Request Path)")
    pdf.body(
        "Browser -> Vercel (nhces.vercel.app) -> /api/* rewrite -> Railway (nhces-api.up.railway.app) "
        "-> Supabase (PostgreSQL) + Cloudflare R2 (models/reports) + MLflow (experiment log). "
        "Airflow DAGs run on a separate Railway service and write directly to Supabase."
    )

    # ── 2. Docker ──────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("2  Docker (Backend)")
    pdf.body(
        "The nhces-backend Dockerfile uses a two-stage build to minimise the final "
        "image size. The builder stage compiles Python packages (including LightGBM "
        "which requires build-essential). The runtime stage copies only the installed "
        "packages and application source, runs as a non-root user (nhces), and exposes "
        "port 8000."
    )
    pdf.sub_heading("Key Build Decisions")
    pdf.bullet([
        "python:3.12-slim base — minimal attack surface, no unnecessary OS packages",
        "libgomp1 required at runtime by LightGBM (OpenMP threading)",
        "Test dependencies (pytest, httpx) excluded from production image",
        "ML model artefacts NOT embedded -- loaded from Cloudflare R2 at startup",
        "Non-root user (nhces) to comply with OWASP container hardening guidelines",
        "HEALTHCHECK via /health endpoint (30s interval, 60s start period for model load)",
    ])
    pdf.sub_heading("Build + Run Commands")
    pdf.code_box(
        "# Build image\n"
        "cd nhces-backend\n"
        "docker build -t nhces-backend:latest .\n\n"
        "# Run locally with .env file\n"
        "docker run -p 8000:8000 --env-file .env nhces-backend:latest\n\n"
        "# Inspect running container\n"
        "docker ps\n"
        "docker logs <container_id> --follow"
    )
    pdf.sub_heading(".dockerignore Key Exclusions")
    pdf.bullet([
        ".env / .env.* -- never copy secrets into the image",
        "tests/ -- pytest suite not needed in production",
        "models/*.pkl -- loaded from R2 at runtime; not embedded",
        "generate_*.py -- PDF generators not needed at runtime",
        "*.pdf -- generated documents served from R2",
    ])

    # ── 3. Railway (Backend) ────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("3  Railway Deployment (Backend)")
    pdf.body(
        "Railway detects nhces-backend/railway.toml at the repo root and deploys "
        "the nhces-backend service as a Docker container. The start command reads "
        "$PORT from Railway's environment so the load balancer can route traffic."
    )
    pdf.sub_heading("railway.toml Settings")
    pdf.code_box(
        "[build]\n"
        "builder        = 'DOCKERFILE'\n"
        "dockerfilePath = 'nhces-backend/Dockerfile'\n\n"
        "[deploy]\n"
        "startCommand        = 'python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT ...'\n"
        "healthcheckPath     = '/health'\n"
        "healthcheckTimeout  = 30\n"
        "restartPolicyType   = 'ON_FAILURE'\n"
        "restartPolicyMaxRetries = 3"
    )
    pdf.sub_heading("First Deploy Steps")
    for i, step in enumerate([
        "Create a new Railway project at railway.app",
        "Connect GitHub repository (Settings -> Source -> GitHub)",
        "Set root directory: nhces-backend/",
        "Add all environment variables (Settings -> Variables) -- see Section 7",
        "Railway auto-deploys on every push to main",
        "Check the Deploy Logs tab for model loading confirmation",
        "Test: curl https://nhces-api.up.railway.app/health",
    ], 1):
        pdf.step(i, step)
    pdf.ln(2)

    pdf.sub_heading("Environment Variables (Railway)")
    pdf.info_box(
        "Set in Railway Dashboard -> Project -> Variables (not committed to Git):\n"
        "SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_KEY, SUPABASE_JWT_SECRET,\n"
        "CLOUDFLARE_R2_ENDPOINT, CLOUDFLARE_R2_ACCESS_KEY, CLOUDFLARE_R2_SECRET_KEY,\n"
        "CLOUDFLARE_R2_BUCKET, MLFLOW_TRACKING_URI, AIRFLOW_API_URL,\n"
        "AIRFLOW_USERNAME, AIRFLOW_PASSWORD, SECRET_KEY, ENVIRONMENT=production,\n"
        "ALLOWED_ORIGINS=https://nhces.vercel.app"
    )

    # ── 4. Vercel (Frontend) ───────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("4  Vercel Deployment (Frontend)")
    pdf.body(
        "The nhces-frontend is a Next.js 14 App Router application deployed to "
        "Vercel. The existing vercel.json rewrite rule proxies /api/* to the "
        "Railway backend so the browser never exposes the Railway URL directly."
    )
    pdf.sub_heading("vercel.json (existing)")
    pdf.code_box(
        '{\n'
        '  "buildCommand": "npm run build",\n'
        '  "outputDirectory": ".next",\n'
        '  "framework": "nextjs",\n'
        '  "rewrites": [\n'
        '    {\n'
        '      "source": "/api/:path*",\n'
        '      "destination": "https://nhces-api.up.railway.app/:path*"\n'
        '    }\n'
        '  ]\n'
        '}'
    )
    pdf.sub_heading("First Deploy Steps")
    for i, step in enumerate([
        "Install Vercel CLI: npm install -g vercel",
        "cd nhces-frontend",
        "vercel login (authenticate with Vercel account)",
        "vercel link (links local dir to Vercel project)",
        "Set environment variables: vercel env add NEXT_PUBLIC_SUPABASE_URL production",
        "Set: NEXT_PUBLIC_SUPABASE_ANON_KEY, NEXT_PUBLIC_API_URL",
        "Deploy: vercel --prod",
        "Subsequent deploys: automatic via GitHub Actions (see Section 6)",
    ], 1):
        pdf.step(i, step)
    pdf.ln(2)
    pdf.sub_heading("Environment Variables (Vercel)")
    pdf.info_box(
        "Set in Vercel Dashboard -> Project -> Settings -> Environment Variables:\n"
        "NEXT_PUBLIC_SUPABASE_URL  = https://<project-ref>.supabase.co\n"
        "NEXT_PUBLIC_SUPABASE_ANON_KEY = <anon/public key>\n"
        "NEXT_PUBLIC_API_URL = https://nhces-api.up.railway.app\n\n"
        "NEVER set SUPABASE_SERVICE_KEY on the frontend -- it is backend-only."
    )

    # ── 5. Airflow DAGs ─────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("5  Airflow DAG Deployment")
    pdf.body(
        "Nine Airflow DAGs manage the iNHCES data pipelines. "
        "All DAGs are in 05_ml_models/05_dags/ and are deployed to the "
        "Airflow dags/ folder on the Railway Airflow service."
    )
    pdf.sub_heading("DAG Registry")
    dags = [
        ("nhces_daily_fx_oil",     "0 4 * * *",       "Daily",     "FX rates + Brent crude", "RED"),
        ("nhces_weekly_materials", "0 4 * * 1",        "Weekly",    "Cement + iron rod prices", "RED"),
        ("nhces_weekly_property",  "0 4 * * 2",        "Weekly",    "Property listing prices", "RED"),
        ("nhces_monthly_macro",    "0 4 1 * *",         "Monthly",   "CPI + lending rate", "GREEN/RED"),
        ("nhces_quarterly_niqs",   "manual",            "Quarterly", "NIQS unit rates (manual trigger)", "RED"),
        ("nhces_quarterly_nbs",    "0 4 1 1,4,7,10 *", "Quarterly", "NBS statistics", "RED"),
        ("nhces_worldbank_annual", "0 4 2 1 *",         "Annual",    "World Bank GDP + CPI bulk refresh", "GREEN"),
        ("nhces_retrain_weekly",   "0 1 * * 0",         "Weekly",    "ML champion retrain (6 tasks)", "AMBER"),
        ("nhces_drift_monitor",    "0 16 * * *",        "Daily",     "PSI drift detection + auto-trigger", "AMBER"),
    ]
    pdf.set_fill_color(*DARK_NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_x(LEFT)
    for h, w in [("DAG ID", 52), ("Schedule", 38), ("Freq", 18), ("Description", 62), ("Level", 16)]:
        pdf.cell(w, LINE_H, h, border=1, fill=True, align="C")
    pdf.ln()
    level_colours = {"RED": (255, 225, 225), "AMBER": (255, 245, 210), "GREEN": (220, 245, 225), "GREEN/RED": (245, 240, 220)}
    for dag_id, sched, freq, desc, level in dags:
        bg = level_colours.get(level, WHITE)
        pdf.set_fill_color(*bg)
        pdf.set_x(LEFT)
        pdf.set_font("Courier", "", 6.5)
        pdf.set_text_color(*DARK_NAVY)
        pdf.cell(52, LINE_H, dag_id, border=1, fill=True)
        pdf.cell(38, LINE_H, sched, border=1, fill=True)
        pdf.set_font("Helvetica", "", 7)
        pdf.cell(18, LINE_H, freq, border=1, fill=True, align="C")
        pdf.cell(62, LINE_H, sanitize(desc), border=1, fill=True)
        pdf.cell(16, LINE_H, level, border=1, fill=True, align="C")
        pdf.ln()
    pdf.ln(3)

    pdf.sub_heading("Airflow Setup on Railway")
    for i, step in enumerate([
        "Create Railway service: airflow-webserver (image: apache/airflow:2.8.0-python3.12)",
        "Create Railway service: airflow-scheduler (same image)",
        "Add PostgreSQL database service (airflow metadata DB)",
        "Set AIRFLOW__CORE__EXECUTOR=LocalExecutor",
        "Mount DAGs via GitHub volume or copy to /opt/airflow/dags/",
        "Import connections: airflow connections import nhces_connections.json",
        "Import variables: airflow variables import nhces_variables.json",
        "Enable all 9 DAGs in the Airflow web UI",
        "Trigger nhces_worldbank_annual manually to populate historical data",
    ], 1):
        pdf.step(i, step)

    # ── 6. GitHub Actions CI/CD ────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("6  GitHub Actions CI/CD")
    pdf.body(
        "The .github/workflows/deploy.yml workflow runs on every push to main. "
        "It runs the 73-test pytest suite and Next.js build in parallel, then "
        "deploys backend to Railway and frontend to Vercel if both pass."
    )
    pdf.sub_heading("Pipeline Stages")
    stages = [
        ("backend-tests",   "ubuntu-latest", "pytest 73 tests",                 "always"),
        ("frontend-build",  "ubuntu-latest", "npm ci + eslint + next build",     "always"),
        ("deploy-backend",  "ubuntu-latest", "railway up --detach + /health",    "main push only"),
        ("deploy-frontend", "ubuntu-latest", "vercel build --prod + deploy",     "main push only"),
    ]
    pdf.set_fill_color(*DARK_NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_x(LEFT)
    for h, w in [("Job", 38), ("Runner", 30), ("Steps", 78), ("Trigger", PAGE_W - 38 - 30 - 78)]:
        pdf.cell(w, LINE_H + 1, h, border=1, fill=True, align="C")
    pdf.ln()
    for job, runner, steps, trigger in stages:
        pdf.set_fill_color(248, 250, 255)
        pdf.set_x(LEFT)
        pdf.set_font("Courier", "", 7.5)
        pdf.set_text_color(*DARK_NAVY)
        pdf.cell(38, LINE_H, job, border=1, fill=True)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.cell(30, LINE_H, runner, border=1, fill=True)
        pdf.cell(78, LINE_H, sanitize(steps), border=1, fill=True)
        pdf.set_text_color(*MID_GREY)
        pdf.cell(PAGE_W - 38 - 30 - 78, LINE_H, trigger, border=1, fill=True, ln=True)
    pdf.ln(3)

    pdf.sub_heading("Required GitHub Secrets")
    secrets = [
        ("RAILWAY_TOKEN",       "Railway API token (Account -> Tokens)"),
        ("RAILWAY_SERVICE_ID",  "Railway service ID for nhces-backend"),
        ("VERCEL_TOKEN",        "Vercel API token (Account -> Tokens)"),
        ("VERCEL_ORG_ID",       "Vercel team/organisation ID"),
        ("VERCEL_PROJECT_ID",   "Vercel project ID for nhces-frontend"),
    ]
    pdf.set_fill_color(*DARK_NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_x(LEFT)
    pdf.cell(52, LINE_H, "Secret Name", border=1, fill=True)
    pdf.cell(PAGE_W - 52, LINE_H, "Value / Source", border=1, fill=True, ln=True)
    for name, desc in secrets:
        pdf.set_fill_color(248, 250, 255)
        pdf.set_x(LEFT)
        pdf.set_font("Courier", "", 7.5)
        pdf.set_text_color(*DARK_NAVY)
        pdf.cell(52, LINE_H, name, border=1, fill=True)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*DARK_GREY)
        pdf.cell(PAGE_W - 52, LINE_H, sanitize(desc), border=1, fill=True, ln=True)
    pdf.ln(3)

    pdf.sub_heading("Adding Secrets")
    pdf.code_box(
        "GitHub repo -> Settings -> Secrets and variables -> Actions\n"
        "-> New repository secret\n\n"
        "# All 5 secrets must be set before the first deploy:\n"
        "RAILWAY_TOKEN, RAILWAY_SERVICE_ID\n"
        "VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID"
    )

    # ── 7. Environment Variables Reference ─────────────────────────────────────
    pdf.add_page()
    pdf.section_title("7  Environment Variables Reference")
    pdf.body(
        "All secrets are managed in the respective platform dashboards. "
        "Copy nhces-backend/.env.example to nhces-backend/.env for local development. "
        "Never commit .env files to Git."
    )
    env_vars = [
        ("SUPABASE_URL",                 "Railway + local", "Yes", "https://<ref>.supabase.co"),
        ("SUPABASE_ANON_KEY",            "Railway + local", "Yes", "Supabase anon/public key"),
        ("SUPABASE_SERVICE_KEY",         "Railway + local", "Yes", "service_role key -- backend only"),
        ("SUPABASE_JWT_SECRET",          "Railway + local", "Yes", "From Supabase Auth settings"),
        ("CLOUDFLARE_R2_ENDPOINT",       "Railway + local", "Yes", "https://<acct>.r2.cloudflarestorage.com"),
        ("CLOUDFLARE_R2_ACCESS_KEY",     "Railway + local", "Yes", "R2 access key ID"),
        ("CLOUDFLARE_R2_SECRET_KEY",     "Railway + local", "Yes", "R2 secret access key"),
        ("CLOUDFLARE_R2_BUCKET",         "Railway + local", "No",  "Default: inhces-storage"),
        ("MLFLOW_TRACKING_URI",          "Railway + local", "No",  "http://<svc>.railway.app:5000"),
        ("MLFLOW_EXPERIMENT",            "Railway + local", "No",  "Default: nhces_cost_estimation"),
        ("AIRFLOW_API_URL",              "Railway + local", "No",  "http://<svc>.railway.app:8080/api/v1"),
        ("AIRFLOW_USERNAME",             "Railway + local", "No",  "Default: admin"),
        ("AIRFLOW_PASSWORD",             "Railway + local", "No",  "Set a strong password in production"),
        ("SECRET_KEY",                   "Railway + local", "Yes", "Strong random string in production"),
        ("ENVIRONMENT",                  "Railway",         "No",  "production (dev default: development)"),
        ("ALLOWED_ORIGINS",              "Railway",         "No",  "https://nhces.vercel.app"),
        ("EIA_API_KEY",                  "Railway + local", "No",  "EIA.gov API key (upgrades Brent to GREEN)"),
        ("FRED_API_KEY",                 "Railway + local", "No",  "FRED API key (upgrades FX to GREEN)"),
        ("NEXT_PUBLIC_SUPABASE_URL",     "Vercel",          "Yes", "Same as SUPABASE_URL"),
        ("NEXT_PUBLIC_SUPABASE_ANON_KEY","Vercel",          "Yes", "Supabase anon key (public)"),
        ("NEXT_PUBLIC_API_URL",          "Vercel",          "No",  "https://nhces-api.up.railway.app"),
    ]
    pdf.set_fill_color(*DARK_NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_x(LEFT)
    for h, w in [("Variable", 62), ("Platform", 26), ("Required", 16), ("Notes", PAGE_W - 62 - 26 - 16)]:
        pdf.cell(w, LINE_H, h, border=1, fill=True, align="C")
    pdf.ln()
    for var, plat, req, note in env_vars:
        req_bg = (210, 240, 215) if req == "Yes" else (245, 245, 245)
        pdf.set_fill_color(248, 250, 255)
        pdf.set_x(LEFT)
        pdf.set_font("Courier", "", 6.5)
        pdf.set_text_color(*DARK_NAVY)
        pdf.cell(62, LINE_H, var, border=1, fill=True)
        pdf.set_font("Helvetica", "", 7)
        pdf.cell(26, LINE_H, sanitize(plat), border=1, fill=True)
        pdf.set_fill_color(*req_bg)
        pdf.cell(16, LINE_H, req, border=1, fill=True, align="C")
        pdf.set_fill_color(248, 250, 255)
        pdf.set_text_color(*DARK_GREY)
        pdf.cell(PAGE_W - 62 - 26 - 16, LINE_H, sanitize(note), border=1, fill=True, ln=True)
    pdf.ln(3)

    # ── 8. Pre-Launch Checklist ────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("8  Pre-Launch Checklist")
    checklist = [
        ("INFRA",  "Supabase schema applied (04_schema.sql + 04_rls_policies.sql)"),
        ("INFRA",  "Supabase seed data applied (04_seed_data.sql) -- remove RED seed in production"),
        ("INFRA",  "DB functions created (04_db_functions.sql) + indexes (04_db_indexes.sql)"),
        ("INFRA",  "DB verification checks pass (04_db_verification.sql)"),
        ("BACKEND","Dockerfile builds without error locally"),
        ("BACKEND","All 73 pytest tests pass: python -m pytest tests/ -q"),
        ("BACKEND","Railway environment variables all set"),
        ("BACKEND","Railway deployment live: curl https://nhces-api.up.railway.app/health"),
        ("BACKEND","R2 bucket inhces-storage created with public access blocked"),
        ("BACKEND","champion_model.pkl uploaded to R2: inhces-storage/models/champion_model.pkl"),
        ("BACKEND","API docs accessible: https://nhces-api.up.railway.app/docs"),
        ("FRONTEND","Vercel environment variables set"),
        ("FRONTEND","next build completes without errors locally"),
        ("FRONTEND","Vercel deployment live: https://nhces.vercel.app"),
        ("FRONTEND","Landing page loads, Estimate form submits, results display"),
        ("CICD",   "5 GitHub Secrets set (RAILWAY_TOKEN etc.)"),
        ("CICD",   "Push to main triggers all 4 GitHub Actions jobs"),
        ("CICD",   "Both deploy jobs show green in Actions tab"),
        ("AIRFLOW","Airflow webserver accessible on Railway"),
        ("AIRFLOW","nhces_connections.json imported"),
        ("AIRFLOW","nhces_variables.json imported"),
        ("AIRFLOW","All 9 DAGs visible and enabled in Airflow UI"),
        ("AIRFLOW","nhces_worldbank_annual triggered manually -- GDP + CPI data loaded"),
        ("AIRFLOW","nhces_retrain_weekly triggered manually -- champion model refreshed"),
        ("SECURITY","RLS policies active -- tested with non-admin user"),
        ("SECURITY","SUPABASE_SERVICE_KEY NOT exposed in any frontend environment variable"),
        ("SECURITY","All .env files in .gitignore and not committed"),
        ("DATA",   "RED-banner data replaced with live API data before any publication"),
        ("DATA",   "AMBER synthetic survey data (O3) replaced with real Delphi survey results"),
    ]
    pdf.set_fill_color(*DARK_NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_x(LEFT)
    pdf.cell(20, LINE_H, "Area", border=1, fill=True, align="C")
    pdf.cell(8, LINE_H, "[ ]", border=1, fill=True, align="C")
    pdf.cell(PAGE_W - 28, LINE_H, "Check", border=1, fill=True, ln=True)
    area_colours = {
        "INFRA": (235, 245, 255), "BACKEND": (240, 255, 240), "FRONTEND": (255, 248, 235),
        "CICD": (250, 240, 255), "AIRFLOW": (255, 252, 235), "SECURITY": (255, 235, 235),
        "DATA": (235, 255, 252),
    }
    for area, item in checklist:
        bg = area_colours.get(area, WHITE)
        pdf.set_fill_color(*bg)
        pdf.set_x(LEFT)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(*DARK_NAVY)
        pdf.cell(20, LINE_H, area, border=1, fill=True, align="C")
        pdf.cell(8, LINE_H, "[ ]", border=1, fill=True, align="C")
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*DARK_GREY)
        pdf.cell(PAGE_W - 28, LINE_H, sanitize(item), border=1, fill=True, ln=True)
    pdf.ln(3)

    pdf.info_box(
        "DATA SOURCE: AMBER -- AI-authored deployment guide. "
        "All placeholder values (Railway service IDs, Supabase project refs, "
        "Cloudflare account IDs, Vercel project IDs) must be replaced with real "
        "values from the respective platform dashboards before deployment. "
        "RED-banner data (synthetic) must be replaced with live API / real survey data "
        "before any research publication. "
        "TETFund NRF 2025 | Dept. of Quantity Surveying, ABU Zaria."
    )

    # Save
    out_path = os.path.join(OUTPUT_DIR, "O6_14_Deployment_Guide.pdf")
    pdf.output(out_path)
    print(f"[OK] {out_path}")
    print(f"     Pages: {pdf.page}")


if __name__ == "__main__":
    generate()

