"""
iNHCES O6-S12 Agent 07 — Code Review Checklist PDF Generator
Produces O6_12_Code_Review_Checklist.pdf for the nhces-backend.

DATA SOURCE: AMBER — checklist is AI-generated; all items must be
verified by the lead developer before sign-off.

TETFund NRF 2025 | Department of Quantity Surveying, ABU Zaria
"""

import os
import sys

# ── Path setup ─────────────────────────────────────────────────────────────────
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, "01_literature_review"))

from generate_o1_pdfs import (
    DocPDF, sanitize,
    DARK_NAVY, GOLD, LIGHT_BLUE, LABEL_BLUE, WHITE,
    DARK_GREY, MID_GREY, CODE_BG, GREEN_BG, RED_BG,
    PAGE_W, LEFT, LINE_H,
)
from fpdf import FPDF
from datetime import date

OUTPUT_DIR = os.path.join(_ROOT, "nhces-backend")

# ── Colour helpers ─────────────────────────────────────────────────────────────
PASS_GREEN  = (200, 235, 200)
WARN_AMBER  = (255, 243, 200)
FAIL_RED    = (245, 215, 215)
INFO_BLUE   = (220, 230, 245)


# ── Checklist PDF ──────────────────────────────────────────────────────────────

class ReviewPDF(DocPDF):
    def header(self):
        self.set_fill_color(*DARK_NAVY)
        self.rect(0, 0, 210, 14, "F")
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*WHITE)
        self.set_xy(5, 4)
        self.cell(PAGE_W, 6, sanitize(
            "iNHCES | TETFund NRF 2025 | ABU Zaria  |  O6-S12 Code Review Checklist"
        ))
        self.set_text_color(*DARK_GREY)
        self.ln(16)

    def footer(self):
        self.set_y(-13)
        self.set_draw_color(*GOLD)
        self.set_line_width(0.4)
        self.line(LEFT, self.get_y(), 198, self.get_y())
        self.set_font("Helvetica", "I", 7.5)
        self.set_text_color(*MID_GREY)
        self.cell(0, 8, sanitize(
            f"O6_12 Code Review Checklist  |  ABU Zaria / TETFund NRF 2025  |  Page {self.page_no()}"
        ), align="C")

    def ds_page(self, level, notes=""):
        """DATA SOURCE banner page."""
        self.add_page()
        colour = {"GREEN": (30, 130, 60), "AMBER": (180, 120, 0), "RED": (160, 30, 30)}[level]
        self.set_fill_color(*colour)
        self.set_text_color(*WHITE)
        self.rect(0, 14, 210, 22, "F")
        self.set_xy(0, 18)
        self.set_font("Helvetica", "B", 13)
        self.cell(210, 8, sanitize(f"DATA SOURCE DECLARATION — {level}"), align="C", ln=True)
        self.set_font("Helvetica", "", 9)
        labels = {
            "GREEN": "Live API / real measured instrument",
            "AMBER": "AI-authored template — verify before use",
            "RED":   "Fully synthetic / fabricated — MUST replace before publication",
        }
        self.cell(210, 7, sanitize(labels[level]), align="C", ln=True)
        self.set_text_color(*DARK_GREY)
        self.set_xy(LEFT, 44)
        if notes:
            self.set_font("Helvetica", "I", 8.5)
            self.multi_cell(PAGE_W, 5.2, sanitize(notes))
        self.ln(3)
        disclaimer = (
            "This document was generated by an AI research assistant "
            "(GitHub Copilot / Claude Sonnet 4.6). It constitutes a structural "
            "template only. All checklist items must be verified by the lead "
            "developer and sign-off authority before any production deployment. "
            "No AI-generated content should be presented as a verified security "
            "or quality audit without independent expert review. "
            "TETFund NRF 2025 | Department of Quantity Surveying, ABU Zaria."
        )
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*MID_GREY)
        self.set_x(LEFT)
        self.multi_cell(PAGE_W, 5, sanitize(disclaimer))

    def section_band(self, title, fill=DARK_NAVY):
        self.ln(5)
        self.set_fill_color(*fill)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 10)
        self.set_x(LEFT)
        self.cell(PAGE_W, 8, sanitize(f"  {title}"), fill=True, ln=True)
        self.set_text_color(*DARK_GREY)
        self.ln(2)

    def checklist_row(self, ref, item, status, note=""):
        """
        status: PASS | WARN | FAIL | N/A
        """
        colours = {
            "PASS": PASS_GREEN,
            "WARN": WARN_AMBER,
            "FAIL": FAIL_RED,
            "N/A":  (230, 230, 230),
        }
        bg = colours.get(status, (240, 240, 240))
        self.set_fill_color(*bg)
        self.set_draw_color(*MID_GREY)
        self.set_line_width(0.2)

        # Reference cell (14 mm)
        self.set_x(LEFT)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*DARK_NAVY)
        self.cell(14, LINE_H, sanitize(ref), border=1, fill=True)

        # Item cell
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*DARK_GREY)
        item_w = 120
        self.cell(item_w, LINE_H, sanitize(item[:75]), border=1, fill=True)

        # Status cell (18 mm)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*DARK_NAVY)
        self.cell(18, LINE_H, sanitize(status), border=1, fill=True, align="C")

        # Note cell (remaining width)
        note_w = PAGE_W - 14 - item_w - 18
        self.set_font("Helvetica", "I", 7.5)
        self.set_text_color(*MID_GREY)
        self.cell(note_w, LINE_H, sanitize(note[:35]), border=1, fill=True, ln=True)

    def checklist_header(self):
        self.set_fill_color(*DARK_NAVY)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 8)
        self.set_x(LEFT)
        cols = [
            (14, "Ref"),
            (120, "Checklist Item"),
            (18, "Status"),
            (PAGE_W - 14 - 120 - 18, "Note"),
        ]
        for w, label in cols:
            self.cell(w, LINE_H + 1, sanitize(label), border=1, fill=True, align="C")
        self.ln()

    def summary_row(self, section, total, passed, warned, failed):
        self.set_x(LEFT)
        self.set_font("Helvetica", "", 9)
        for val, w in [
            (section, 70), (str(total), 20), (str(passed), 20),
            (str(warned), 20), (str(failed), 20),
        ]:
            bg = PASS_GREEN if val == str(passed) and passed == total else (255, 255, 255)
            if val == str(failed) and failed > 0:
                bg = FAIL_RED
            self.set_fill_color(*bg)
            self.cell(w, LINE_H, sanitize(str(val)), border=1, fill=True, align="C")
        self.ln()


# ── Checklist data ─────────────────────────────────────────────────────────────

def _build_sections():
    """Returns a list of (section_title, [(ref, item, status, note)])."""

    sections = []

    # 1. Authentication & Authorisation
    sections.append(("1  Authentication & Authorisation", [
        ("A1",  "JWT tokens validated on every protected endpoint",
         "PASS", "python-jose HS256"),
        ("A2",  "Supabase JWT secret loaded from env var (not hardcoded)",
         "PASS", "config.py"),
        ("A3",  "bearer_optional used for optional-auth endpoints",
         "PASS", "get_optional_user"),
        ("A4",  "Role checks enforced: researcher/admin for /pipeline",
         "WARN", "Verify prod roles"),
        ("A5",  "401 returned for missing/invalid JWT (not 403)",
         "PASS", "auth.py"),
        ("A6",  "get_optional_user returns None (not raise) on missing token",
         "PASS", "projects router"),
        ("A7",  "JWT algorithm pinned to HS256 (not 'any')",
         "PASS", "jwt.decode options"),
        ("A8",  "No secrets in logs or error responses",
         "PASS", "reviewed main.py"),
    ]))

    # 2. Input Validation
    sections.append(("2  Input Validation (Pydantic)", [
        ("V1",  "EstimateRequest: floor_area_sqm gt=0 le=100000",
         "PASS", "schemas/estimate.py"),
        ("V2",  "EstimateRequest: num_floors ge=1 le=100",
         "PASS", "schemas/estimate.py"),
        ("V3",  "EstimateRequest: location_state min_length=2 max_length=60",
         "PASS", "schemas/estimate.py"),
        ("V4",  "EstimateRequest: building_type is enum (not free text)",
         "PASS", "BuildingType enum"),
        ("V5",  "ProjectCreate: title min_length=3 max_length=200",
         "PASS", "schemas/project.py"),
        ("V6",  "ProjectCreate: target_cost_ngn gt=0 when present",
         "PASS", "Field(gt=0) optional"),
        ("V7",  "UUID fields use pydantic UUID4 type (validated format)",
         "PASS", "project_id UUID4"),
        ("V8",  "Query params validated: years ge=1 le=25 for /macro/history",
         "PASS", "Query(ge=1,le=25)"),
        ("V9",  "422 returned for invalid enum values (not 400 or 500)",
         "PASS", "test suite verified"),
        ("V10", "All string inputs sanitised before DB insert (via Supabase SDK)",
         "PASS", "parameterised queries"),
    ]))

    # 3. Database & Supabase
    sections.append(("3  Database & Supabase", [
        ("D1",  "Service-role key used only in backend (never exposed to frontend)",
         "PASS", "config.py + RLS"),
        ("D2",  "Supabase client is singleton (lru_cache)",
         "PASS", "database.py"),
        ("D3",  "RLS policies defined for all 16 tables",
         "PASS", "04_rls_policies.sql"),
        ("D4",  "Predictions stored with user_id='anonymous' when unauthenticated",
         "PASS", "estimate router"),
        ("D5",  "DB insert failures in /estimate are non-fatal (caught, logged)",
         "PASS", "test verified"),
        ("D6",  "health_check() uses lightweight query (limit 1)",
         "PASS", "database.py"),
        ("D7",  "No raw SQL strings (Supabase SDK only — parameterised)",
         "PASS", "no raw SQL"),
        ("D8",  "Sensitive fields (keys, passwords) not returned in API responses",
         "PASS", "response models"),
        ("D9",  "Connection pool: Supabase SDK handles pooling via PostgREST",
         "PASS", "N/A - SDK"),
        ("D10", "Database indexes exist for high-frequency query columns",
         "PASS", "04_db_indexes.sql"),
    ]))

    # 4. ML Inference & Data Pipeline
    sections.append(("4  ML Inference & Data Pipeline", [
        ("M1",  "Champion model loaded at startup (lifespan), not per-request",
         "PASS", "main.py lifespan"),
        ("M2",  "Model loading has R2 -> local -> synthetic fallback chain",
         "PASS", "inference.py"),
        ("M3",  "CHAMPION_MAPE_PCT (13.66%) used for confidence interval",
         "PASS", "inference.py"),
        ("M4",  "Feature vector shape (1, 14) validated before predict()",
         "WARN", "Add assert in prod"),
        ("M5",  "SHAP computation falls back gracefully on failure",
         "PASS", "explainer.py"),
        ("M6",  "Temporal projections capped at 5 years (no extrapolation beyond)",
         "PASS", "temporal.py"),
        ("M7",  "Inflation rate anchored to real World Bank CPI (O2 data)",
         "PASS", "AMBER - partial"),
        ("M8",  "Synthetic data flag (is_synthetic) returned in API response",
         "PASS", "EstimateResponse"),
        ("M9",  "Data freshness (GREEN/AMBER/RED) propagated from DB to response",
         "PASS", "feature_prep.py"),
        ("M10", "Feature engineering uses I(1)/I(2)* transforms (O5 parity)",
         "PASS", "feature_prep.py"),
    ]))

    # 5. API Design & Error Handling
    sections.append(("5  API Design & Error Handling", [
        ("E1",  "503 returned when feature prep fails (not 500)",
         "PASS", "estimate router"),
        ("E2",  "404 returned when project not found (not 500)",
         "PASS", "projects router"),
        ("E3",  "400 returned for unknown macro variable (not 422 or 500)",
         "PASS", "macro router"),
        ("E4",  "All router errors use HTTPException (not bare raise)",
         "PASS", "reviewed"),
        ("E5",  "Logger used for non-fatal warnings (not print())",
         "PASS", "all routers"),
        ("E6",  "CORS configured: allowed_origins from env (not *)",
         "PASS", "config.origins_list"),
        ("E7",  "API versioning: all routes under /v1 or documented",
         "WARN", "No versioning yet"),
        ("E8",  "Response models defined for all routes (no bare dict returns)",
         "PASS", "Pydantic models"),
        ("E9",  "HTTP methods correct: GET read-only, POST create, PUT update",
         "PASS", "reviewed"),
        ("E10", "Pagination implemented for list endpoints (/projects)",
         "PASS", "page/limit params"),
    ]))

    # 6. Security (OWASP Top 10)
    sections.append(("6  Security — OWASP Top 10", [
        ("S1",  "A01 Broken Access Control: RLS on all tables + JWT checks",
         "PASS", "auth.py + RLS"),
        ("S2",  "A02 Cryptographic Failures: JWT secret min 32 chars in prod",
         "WARN", "Enforce in deploy"),
        ("S3",  "A03 Injection: Supabase SDK parameterises all queries",
         "PASS", "No raw SQL"),
        ("S4",  "A04 Insecure Design: service_role key not exposed to frontend",
         "PASS", ".env.example"),
        ("S5",  "A05 Security Misconfiguration: CORS origins locked in prod",
         "WARN", "Set ALLOWED_ORIGINS"),
        ("S6",  "A06 Vulnerable Components: requirements pinned to exact versions",
         "PASS", "requirements.txt"),
        ("S7",  "A07 ID & Authentication: HTTPBearer + Supabase GoTrue",
         "PASS", "auth.py"),
        ("S8",  "A08 Software Integrity: model loaded from R2 with known key",
         "WARN", "Add checksum"),
        ("S9",  "A09 Logging: structured logger configured (no secret leakage)",
         "PASS", "logging module"),
        ("S10", "A10 SSRF: Airflow URL from env var (validated format expected)",
         "WARN", "Validate URL format"),
    ]))

    # 7. Test Coverage
    sections.append(("7  Test Coverage Summary", [
        ("T1",  "GET / health endpoint — 5 tests",
         "PASS", "test_api.py"),
        ("T2",  "GET /health DB status — 5 tests",
         "PASS", "test_api.py"),
        ("T3",  "GET /docs, /redoc, /openapi.json — 4 tests",
         "PASS", "test_api.py"),
        ("T4",  "CORS origin and preflight — 2 tests",
         "PASS", "test_api.py"),
        ("T5",  "POST /estimate success path — 16 tests",
         "PASS", "test_estimate.py"),
        ("T6",  "POST /estimate Pydantic validation — 7 tests",
         "PASS", "test_estimate.py"),
        ("T7",  "POST /estimate resilience (503, non-fatal DB) — 2 tests",
         "PASS", "test_estimate.py"),
        ("T8",  "GET /macro snapshot — 7 tests",
         "PASS", "test_pipeline.py"),
        ("T9",  "GET /macro/history — 6 tests",
         "PASS", "test_pipeline.py"),
        ("T10", "GET /projects unauthenticated — 4 tests",
         "PASS", "test_pipeline.py"),
        ("T11", "GET/POST /projects authenticated — 8 tests",
         "PASS", "test_pipeline.py"),
        ("T12", "GET /pipeline DAG status — 7 tests",
         "PASS", "test_pipeline.py"),
        ("T13", "Total: 73 tests, 73 PASSED in 1.73 s",
         "PASS", "pytest run 2026-04-27"),
        ("T14", "Missing: integration tests (Supabase live)",
         "WARN", "Pre-launch task"),
        ("T15", "Missing: load tests (response time < 3 s target)",
         "WARN", "Pre-launch task"),
    ]))

    # 8. Code Quality
    sections.append(("8  Code Quality", [
        ("Q1",  "All imports at module level (except lazy imports justified)",
         "PASS", "reviewed"),
        ("Q2",  "No bare except: clauses — all except Exception",
         "PASS", "reviewed"),
        ("Q3",  "lru_cache used correctly for singletons (settings, db client)",
         "PASS", "config.py, db.py"),
        ("Q4",  "Type hints on all public functions",
         "WARN", "Partial coverage"),
        ("Q5",  "No hardcoded credentials in source code",
         "PASS", "all use env vars"),
        ("Q6",  "requirements.txt pinned to exact versions",
         "PASS", "reviewed"),
        ("Q7",  "No unused imports or dead code in routers",
         "PASS", "reviewed"),
        ("Q8",  "Consistent naming: snake_case functions, UPPER_CASE constants",
         "PASS", "reviewed"),
        ("Q9",  "Pydantic models separate from DB models (schemas/ vs models/)",
         "PASS", "schemas/ dir"),
        ("Q10", "All TODO/PLACEHOLDER comments resolved before deployment",
         "WARN", "Audit before launch"),
    ]))

    return sections


# ── Summary tallies ────────────────────────────────────────────────────────────

def _tally(items):
    p = sum(1 for _, _, s, _ in items if s == "PASS")
    w = sum(1 for _, _, s, _ in items if s == "WARN")
    f = sum(1 for _, _, s, _ in items if s == "FAIL")
    return len(items), p, w, f


# ── Main generator ─────────────────────────────────────────────────────────────

def generate():
    pdf = ReviewPDF(
        doc_name="O6_12 Code Review Checklist",
        doc_subtitle="iNHCES Backend — Agent 07",
    )

    # Cover
    pdf.add_page()
    pdf.set_fill_color(*DARK_NAVY)
    pdf.rect(0, 18, 210, 55, "F")
    pdf.set_xy(0, 26)
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(*WHITE)
    pdf.cell(210, 9, sanitize("O6-S12: Code Review Checklist"), align="C", ln=True)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(200, 215, 235)
    pdf.cell(210, 7, sanitize("iNHCES Backend — Agent 07 Sign-Off"), align="C", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*LIGHT_BLUE)
    pdf.cell(210, 6, sanitize("Intelligent National Housing Cost Estimating System (iNHCES)"), align="C", ln=True)
    pdf.cell(210, 6, sanitize("TETFund NRF 2025  |  Department of Quantity Surveying, ABU Zaria"), align="C", ln=True)
    pdf.set_draw_color(*GOLD)
    pdf.set_line_width(0.8)
    pdf.line(30, 76, 180, 76)
    pdf.set_xy(LEFT, 84)
    pdf.set_text_color(*DARK_GREY)
    meta = [
        ("Session:",     "O6-S12  |  Agents 06 (QA) + 07 (Code Review)"),
        ("Date:",        date.today().strftime("%d %B %Y")),
        ("Scope:",       "nhces-backend/  (FastAPI + ML + Supabase + Airflow)"),
        ("Test run:",    "73 tests | 73 PASSED | 0 FAILED  (pytest 9.0.3, Python 3.12.5)"),
        ("Data source:", "AMBER - AI-generated checklist; verify before sign-off"),
        ("Status:",      "PASS=72 / WARN=11 / FAIL=0  |  Ready for S13 (Documentation)"),
    ]
    for label, val in meta:
        pdf.set_x(LEFT)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*DARK_NAVY)
        pdf.cell(38, 6.5, sanitize(label))
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*DARK_GREY)
        pdf.cell(PAGE_W - 38, 6.5, sanitize(val), ln=True)

    # DATA SOURCE page
    pdf.ds_page(
        "AMBER",
        notes=(
            "This code review checklist was generated by an AI assistant. "
            "Every PASS / WARN item must be manually verified by the lead "
            "developer before production deployment. "
            "WARN items must be resolved or risk-accepted before launch. "
            "DATA SOURCE: AMBER — AI-authored template."
        ),
    )

    # ── Section pages ──────────────────────────────────────────────────────────
    sections = _build_sections()
    total_all = passed_all = warned_all = failed_all = 0

    for section_title, items in sections:
        pdf.add_page()
        pdf.section_band(section_title)
        pdf.checklist_header()
        for ref, item, status, note in items:
            pdf.checklist_row(ref, item, status, note)
        t, p, w, f = _tally(items)
        total_all += t; passed_all += p; warned_all += w; failed_all += f
        pdf.ln(3)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*MID_GREY)
        pdf.set_x(LEFT)
        pdf.cell(PAGE_W, 5, sanitize(
            f"Section tally: {t} items | {p} PASS | {w} WARN | {f} FAIL"
        ), ln=True)

    # ── Summary table ──────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_band("Summary — Code Review Sign-Off")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*DARK_GREY)
    pdf.set_x(LEFT)
    pdf.multi_cell(PAGE_W, 5.2, sanitize(
        "The table below summarises the agent-reviewed checklist results. "
        "All WARN items must be resolved or formally risk-accepted by the "
        "lead developer before the system is promoted to production. "
        "No FAIL items were found; this indicates structural compliance "
        "with the design patterns specified in O6-S1 through S11."
    ))
    pdf.ln(3)

    # Summary table header
    pdf.set_fill_color(*DARK_NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_x(LEFT)
    for label, w in [("Section", 70), ("Total", 20), ("PASS", 20), ("WARN", 20), ("FAIL", 20)]:
        pdf.cell(w, LINE_H + 1, sanitize(label), border=1, fill=True, align="C")
    pdf.ln()

    # Summary rows
    for section_title, items in sections:
        t, p, w, f = _tally(items)
        short = section_title.split("  ")[1][:38] if "  " in section_title else section_title[:38]
        pdf.summary_row(short, t, p, w, f)

    # Total row
    pdf.set_fill_color(*DARK_NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_x(LEFT)
    for val, w in [
        ("TOTAL", 70), (str(total_all), 20), (str(passed_all), 20),
        (str(warned_all), 20), (str(failed_all), 20),
    ]:
        pdf.cell(w, LINE_H + 1, sanitize(val), border=1, fill=True, align="C")
    pdf.ln()

    pdf.ln(6)
    pdf.sub_heading("Sign-Off Criteria")
    pdf.bullet([
        "All FAIL items must be resolved before any production deployment.",
        "All WARN items must be risk-accepted in writing by the lead developer.",
        "The test suite (73 tests) must remain at 100% PASS after any fix.",
        "A second independent review is recommended for security items (S1-S10).",
    ])

    pdf.ln(4)
    pdf.sub_heading("Outstanding WARN Items — Action Required")
    warn_items = [
        (ref, item, note)
        for _, items in sections
        for ref, item, status, note in items
        if status == "WARN"
    ]
    for ref, item, note in warn_items:
        pdf.set_x(LEFT + 4)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(*DARK_GREY)
        pdf.cell(12, 5.5, sanitize(ref))
        pdf.cell(PAGE_W - 12 - 4, 5.5, sanitize(f"{item}  [{note}]"), ln=True)

    pdf.ln(4)
    pdf.info_box(
        "DATA SOURCE: AMBER — This checklist was generated by GitHub Copilot / "
        "Claude Sonnet 4.6 on " + date.today().strftime("%d %B %Y") + ". "
        "It is a template only. All items require human verification. "
        "No AI-generated checklist constitutes a formal security audit. "
        "TETFund NRF 2025 | Dept. of Quantity Surveying, ABU Zaria."
    )

    # Save
    out_path = os.path.join(OUTPUT_DIR, "O6_12_Code_Review_Checklist.pdf")
    pdf.output(out_path)
    print(f"[OK] {out_path}")
    print(f"     Pages: {pdf.page}  |  Items: {total_all}  "
          f"|  PASS: {passed_all}  WARN: {warned_all}  FAIL: {failed_all}")


if __name__ == "__main__":
    generate()
